# Generated by Django 2.2 on 2019-04-22 10:29

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=10, null=True, verbose_name='Kategori İsmi')),
            ],
            options={
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Başlık bilgisi burada girilir.', max_length=100, null=True, verbose_name='Başlık ')),
                ('content', models.TextField(max_length=5000, null=True, verbose_name='İçerik')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
                ('unique_id', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, help_text='Kapak Fotoğrafı Yükleyiniz', null=True, upload_to=posts.models.upload_to, verbose_name='Resim')),
                ('kategoriler', models.ManyToManyField(null=True, related_name='blog', to='posts.Kategori')),
            ],
            options={
                'verbose_name': 'Gönderi',
                'verbose_name_plural': 'Gönderiler',
                'ordering': ['-id'],
            },
        ),
    ]
